//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forme.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Linija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Linija()
        {
            this.Karta = new HashSet<Karta>();
        }
    
        public int linija_id { get; set; }
        public string broj_linije { get; set; }
        public string polaziste { get; set; }
        public string odrediste { get; set; }
        public string datum_i_vrijeme_polaska { get; set; }
        public int udaljenost { get; set; }
        public int autoprijevoznik_id { get; set; }
        public int broj_mjesta { get; set; }
        public int broj_slobodnih_mjesta { get; set; }
    
        public virtual Autoprijevoznik Autoprijevoznik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Karta> Karta { get; set; }
    }
}
